### ISSUE TITLE
Collation: Unable to claim rewards after successful claim

### ISSUE THREAD

**Issue by 0xneuratic** [ATOR-Development/valid-ator#6]
A number of users are facing issues with claiming tokens / claiming tokens after a successful claim. This appears to be a frontend limitation. 

Some flavours of issues with details
> Claim is "Waiting for Oracle Update" 
Checked the wallet, there is no ERC20 Token Transaction, also no transaction with metothID 0xfcd6d195
0x981F118EdbD9e360863dFA283f05200804825b1A

> I successfully claimed one time but now it’s not possible anymore to claim
0xf198Dd229639D53dB9121DecA7e7B6472555790D
0x6c495E23969ba440D3B7d010A1268bdC098DCba5

Other users who faced this issue (again, received ATOR successfully once but can't claim henceforth)
0xD6FA492088B1239B075B33fA2452bb2DDB9948a1

**Comment by kanshi** [comment]
Seems to be a performance / scaling issue - (tl;dr) validator gets CPU maxed for too long, becomes 'too busy' forcing the monitoring software to restart it (following our service monitoring and restart policy).

The issue in detail is that it takes over 2.5 minutes for a (one-core) Node.js to evaluate the state of the live version of the distribution contract. Since we're live monitoring each service run in the mesh, and its health-check is failing for an extended period of time it gets restarted. Node.js is one-core by design so we can either:
- (hotfix - applied, short term solution) change the restart policy to allow for extended periods of service unavailability (15 minutes),
- (recommended code update - long term solution) deploy multiple validators and implement necessary task synchronization so they work in a cluster,
- (alternative code update - mid term solution) break out the cpu intensive tasks into worker processes allowing validator to use all cores assigned to it.

Hotfix has been applied and we will review what to do to accounts with pending transfers and apply some sort of an automated fix.

**Comment by kanshi** [comment]
Can you provide addresses?

**Comment by 0xneuratic** [comment]
The issue was present whilst the oracle was unresponsive (downtime when no reward outflow occurred). I believe this was due to either onionoo/the cluster being down. The users who faced the issue can claim again. Will close for now.
